spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123456789
  profiles:
    active: prod
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

server:
  port: 9000
  servlet.context-path: /webapplication

cache:
  enabled: true
  cacheType: LRU
  capacityCache: 2 #default 10
  cacheResetFrequency: 300000