spring:
  application.name: demo-project
  profiles.active: local

spring.data.mongodb.uri: ${MONGO_URI:mongodb://localhost:27017/user}

---
spring:
  profiles: local

server:
  port: 9000
  servlet.context-path: /user